application:
  some-property: testValue
spring:
  profiles:
      include: swagger
  data:
      mongodb:
          uri: mongodb://mongodb:27017
          database: VTube
s3:
  region: test
  accessKey: testkey
  secretKey: sectretKey